site_name: Network 101
site_description: Network 101 课程讲义
site_author: LUG@UESTC
#site_url: https://network-101.uestc.app/
repo_name: uestclug/network-101
repo_url: https://github.com/uestclug/network-101
copyright: Brought to you by <a href="https://uestclug.github.io/">LUG@UESTC</a>. Available freely under the <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0 license</a>.

theme:
  name: 'material'
  language: 'zh'
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
  icon:
    logo: fontawesome/soild/network-wired
    repo: octicons/mark-github-16
  features:
    - navigation.top

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.def_list
  - attr_list
  - toc:
      permalink: true

extra:
  social:
    - icon: octicons/globe-16
      link: https://uestclug.github.io/

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js'

extra_css:
  - 'css/extra.css'

nav:
    - 负一：计划规格:
        - 章节编写指导: Spec/writing.md
    - 序: preface.md
    - 零：欢迎:
        - 欢迎: index.md
        - 功劳簿: credits.md
    - 跋: postface.md
